package model.type;

public enum KingdomValue {
	CELLAR, CHAPEL, MOAT, HARBINGER, MERCHANT, VASSAL, VILLAGE, WORKSHOP, BUREAUCRAT, GARDENS,
	MILITIA, MONEYLENDER, POACHER, REMODEL, SMITHY, THRONE_ROOM, BANDIT, COUNCIL_ROOM, FESTIVAL,
	LABORATORY, LIBRARY, MARKET, MINE, SENTRY, WITCH, ARTISAN, CHANCELLOR, WOODCUTTER, FEAST, SPY,
	THIEF, ADVENTURER
}
