package model.type;

public enum RealmValue {
	WORKSHOP, ADVENTURER, LIBRARY, LUMBERJACK, BUREAUCRAT, CELLAR, CHANCELLOR, COUNCIL_CHAMBER,
	CHAPEL, MOAT, SPY, FEAST, FESTIVAL, FORGE, LABORATORY, MARKET, MILITIA, MINE, PAWNSHOP,
	RENOVATION, THRONE_ROOM, WITCH, VILLAGE, THIEF, YARD
}
